require:
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Layout/LineLength:
  Max: 120

Metrics:
  Enabled: false

# I haven't benchmarked this, but it's less readable, and encoding problems
# are a PITA to debug
Performance/UnfreezeString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
